config/routes.rb
RP::Application.routes.draw do
  resources :offerings
  resources :editions

  get 'rp_events/show'

  get 'rp_events/show_page'

  get 'rp_events/index'

  get 'rp_events/new'

  get 'rp_events/create'

  get 'rp_events/update'

  get 'rp_events/destroy'

  get 'scraper/new'
  post 'scraper/create'
  post 'scraper/init'

  get 'finders/create'
  post 'finders/create'

  concern :picable do
    member do
      get 'editpic' # Open dialog to acquire an image from various sources
      get 'glean/:what', :action => 'glean', :what => /titles|descriptions|images|feeds|table|card|masonry|slider/, :as => 'glean'
    end
  end

  concern :collectible do
    member do
      get 'touch'
      get 'associated'
      patch 'collect'
      get 'card' # Provide a card for display via JSON
    end
  end

  concern :taggable do
    member do
      get 'tag' # Present the dialog for tagging and commenting
      patch 'tag'
      get 'lists'  # Present the dialog for managing the lists it's on
      patch 'lists'
    end
  end

  get 'search/index'

  resources :recipe_pages, :concerns => [:taggable, :collectible, :picable]

  resources :page_refs, :concerns => [:taggable, :collectible, :picable] do
    collection do
      get 'tag'
      put 'create'
      post 'create'
    end
  end

  resources :referments, :only => [:show, :create, :update, :destroy] do
    collection do
      put 'create'
    end
  end

  resources :tagsets

  resources :answers

  if Rails.env.staging?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  get "admin/toggle"
  resources :feed_entries, :except => [:index, :create, :new], :concerns => [:taggable, :collectible, :picable]

  resources :suggestions do
    member do
      get 'results'
    end
  end

  if Rails.env.development? || Rails.env.test?
    get "integers" => 'integers#index'
  end

  post '/votes/:entity/:id' => 'votes#create', :entity => /recipe|feed|feed_entry|list|product|site|user|referent/

  get "redirect/go", :as => "goto"
  put "redirect/go"
  get '/auth/failure' => 'authentications#failure'
  get 'defer_invitation' => 'application#defer_invitation'
  get 'menu' => 'application#menu'
  resources :authentications

  get '/auth/:provider/callback' => 'authentications#create'
  post '/auth/:provider/callback' => 'authentications#create'

  devise_for :users, :skip => [:registrations], :controllers => {
                       :sessions => 'sessions',
                       :passwords => 'passwords',
                       :invitations => 'invitations',
                   }

  match 'users', :controller => 'users', :action => 'index', :via => [:get, :post]

  devise_scope :user do
    put "/users/password/new" => 'passwords#new' # To handle redirects from edit
    post "/users/register" => "registrations#create", :as => "user_registration"
    get "/users/sign_up" => "registrations#new", :as => "new_user_registration"
    get "/users/edit" => "registrations#edit", :as => "edit_user_registration"
    get "/users/cancel" => "registrations#cancel", :as => "cancel_user_registration"
    put "/users" => "registrations#update"
    delete "/users" => "registrations#destroy"
    get "/users/sign_out" => "sessions#destroy"
    patch "/users" => "registrations#update"

    get "/users/invitation/divert" => "invitations#divert", :as => "divert_user_invitation"

  end

  authenticate do
    notify_to :users, with_devise: :users, controller: 'users/notifications_with_devise'
  end

  get 'users/profile' => 'users#profile'
  get 'users/identify' => 'users#identify'
  get 'users/:id/recent' => 'users#recent', :as => "user_recent"
  get 'users/:id/recent' => 'users#recent', :as => "user_root"
  get 'users/:id/collection' => 'users#collection', :as => "collection_user"
  get 'users/:id/biglist' => 'users#biglist', :as => "user_biglist"
  resources :users, :except => [:index, :create], :concerns => [ :picable, :taggable, :collectible] do
    member do
      get 'match_friends'
      get 'notify'
      get 'acquire' # Acquire a recipe (etc.)
      post 'follow'
      get 'getpic'
      patch 'sendmail'
      get 'unsubscribe'
      get 'sendmail', :as => "mailto"
    end
  end

  post '/list' => 'lists#create', :as => 'create_list'
  resources :lists, except: [:index, :create], :concerns => [:picable, :taggable, :collectible] do
    member do
      post 'pin' # Add an entity to a list
      get 'contents'
    end
  end
  match 'lists', :controller => 'lists', :action => 'index', :via => [:get, :post]

  post '/site' => 'sites#create', :as => 'create_site'
  resources :sites, except: [:index, :create], :concerns => [:picable, :collectible, :taggable] do
    member do
      post 'absorb'
      get 'feeds'
      post 'approve' # (Admin only) approve the site for presentation
    end
  end
  match 'sites', :controller => 'sites', :action => 'index', :via => [:get, :post]

  resources :image_references #, :except => [:index, :create]
  resources :gleanings
  resources :mercury_results

  post '/feed' => 'feeds#create', :as => 'create_feed'
  resources :feeds, :except => [:index, :create], :concerns => [:picable, :collectible, :taggable] do
    member do
      get 'refresh' # Refresh the feed's entries
      get 'contents'
      post 'approve' # (Admin only) approve the feed for presentation
      post 'rate'
    end
  end
  match 'feeds', :controller => 'feeds', :action => 'index', :via => [:get, :post]

  resources :tag_selections

  post '/tag' => 'tags#create', :as => 'create_tag'
  resources :tags, except: [:index, :create] do
    member do
      post 'associate'
      get 'owned'
      get 'associated'
      post 'define'
    end
    collection do
      get 'list'
      get 'typify'
      get 'match'
    end
  end
  match 'tags', :controller => 'tags', :action => 'index', :via => [:get, :post]

  match 'search', :controller => 'search', :action => 'index', :via => :get
=begin
  post 'collection/update'
  get "collection/refresh"
  get "collection/feed"
  get "collection/show", as: 'collection_show'
  get "collection/new"
  get "collection/edit"
  post "collection/create"
  get "collection/relist"

  get "stream/stream"
  get "stream/buffer_test"
=end

  get 'iframe/create'
  get 'admin/data'
  get 'admin/control'

  resources :feedback, :only => [:new, :create]
  resources :expressions
  resources :referents, :concerns => [:picable, :collectible, :taggable] do
    member do
      get 'associated'
    end
  end
  resources :ratings
  resources :scales

  resources :recipes, :concerns => [:picable, :collectible, :taggable] do
    member do
      get 'piclist'
      get :recipe_page
      post :recipe_page
      resource :recipe_contents do
        get 'annotate'
        patch 'annotate'
        get 'tag'
        patch 'tag'
      end
    end
    collection do
      get 'capture'
      post 'parse'
    end
  end
  get '/revise', :to => 'recipes#revise'
  get '/scrape', :to => 'page_refs#scrape'

  get '/home', :to => 'pages#home'
  get '/privacy', :to => 'pages#privacy'
  get '/popup/:name', :to => 'pages#popup'
  get '/popup', :to => 'pages#popup'
  get '/share', :to => 'pages#share'
  get '/tell_me_more', :to => 'pages#tell_me_more'
  get '/contact', :to => 'pages#contact'
  get '/about', :to => 'pages#about'
  get '/mission', :to => 'pages#mission'
  get '/welcome', :to => 'pages#welcome'
  get '/faq', :to => 'pages#faq'
  get '/admin', :to => 'pages#admin'
  get '/sprites', :to => 'pages#sprites'
  get '/cookmark', :to => 'pages#cookmark'
  get '/collect', :to => 'pages#collect'
  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'
  root :to => 'pages#root'

end

app/controllers/recipe_contents_controller.rb
class RecipeContentsController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy, :annotate, :tag]
  before_action :login_required

  def edit
  end

  # Actions for getting and accepting a new tag
  # POST submits new tag
  # GET returns form
  def tag
    rcparams = params[:recipe][:recipeContents]
    @content = rcparams[:content]
    if params[:button_name] != 'Cancel' && rcparams[:tagname]  # No tag parameters => open dialog
      # If the submission is successful, we redirect to #annotate
      if rcparams[:tagname].blank?
        @recipe.errors.add :base, "You need to name that name!"
      elsif tag = Tag.assert(rcparams[:tagname], Tag.typenum(rcparams[:tagtype]), extant_only: true)
        flash[:popup] = "Name was there all along."
      elsif !(tag = Tag.assert rcparams[:tagname], Tag.typenum(rcparams[:tagtype]))
        @recipe.errors.add :base, 'Couldn\'t make new name'
      elsif tag.errors.any?
        # Report errors and re-enter dialog
        @recipe.errors.add :base, tag.full_messages
      else
        flash[:popup] = "'#{tag.name}' successfully added as #{tag.typename}!"
      end
    end
    # We open the tag dialog if this is the initial call, or a Save failed
    @form_name, @form_title = 'newtag_form', 'Define New Name' if rcparams[:tagname].nil? || @recipe.errors.any?
    render :annotate
  end

  # Modify the content HTML to mark a selection with a parsing tag
  def annotate
    redirect_to :show unless rcparams = params[:recipe][:recipeContents]
    @content = rcparams[:content]
    tag if rcparams[:token] == 'tag'
    ps = ParserServices.new entity: @recipe, input: @content
    # This is a two-, possibly three-phase process:
    # 1) a selection from the browser directs attention to a range of text, which generates a CSS path for an element to parse
    # 2) this so-called parse_path is attempted to be parsed. If it doesn't work because of a findable tag, a dialog is presented
    #    for the user to decide how to handle the tag;
    # 3) the user says to enter the problematic tag directly into the dictionary, or specifies an existing tag for what
    #    was meant by the problematic tag. The latter can be optionally entered as a synonym of the intended name.
    if rcparams[:anchor_path].present? # Initial annotation on browser selection
      logger.debug "Annotating with anchor_path = '#{rcparams[:anchor_path]}'"
      @annotation, @parse_path = ps.annotate_selection *rcparams.values_at(:token, :anchor_path, :anchor_offset, :focus_path, :focus_offset)
    elsif @parse_path = rcparams[:parse_path] # Specifying an element of the DOM
      if !(@tagname = rcparams[:tagname])
        logger.debug "Looking for tag at '#{@parse_path}'"
        @annotation = ps.parse_on_path @parse_path do |tagtype, tagname|
          @tagtype, @tagname = tagtype, tagname
        end
        if @tagname
          @form_name = 'tagtype_form'
        else
          @parse_path = nil
        end
      else # There IS a tagname: use that as a tag
        noko_elmt = ps.extract_via_path @parse_path
        @tagtype = rcparams[:tagtype]
        @annotation = rcparams[:content]
        # @tagname of type @tagtype is a mystery tag previously identified by a failed parse.
        if params[:button_name] != 'Cancel'
          logger.debug "Use tag '#{@tagname}' of type '#{@tagtype}' at path '#{@parse_path}'"
          # The logic here is as follows, for sorting out words.
          # -- '@tagname' is the questionable tag
          # -- 'rcparams[:replacement]' is the id of a tag selected by the user to serve in its place
          # -- 'rcparams[:assert]' is set if that tag will be added to the dictionary
          # If there's no replacement tag, the term is just accepted into the dictionary as a new instance of the tagtype.
          # If there IS a non-nil replacement, that's what we understand the term to mean. If, then, assert is set,
          # the questionable term will get added to the dictionary as a synonym for the replacement. If not, the alias
          # is accepted and added to the Seeker as such.
          # No tagname has been parsed out; proceed to parse the entity denoted by the parse path
          if (replacement = rcparams[:replacement]).present?
            old_tag = Tag.find_by id: replacement
            if rcparams[:assert]
              new_tag = Tag.assert @tagname, @tagtype
              new_tag.absorb old_tag, false
            end
            value = old_tag.name
          else
            # No replacement provided => simply assert the tag into the dictionary
            value = @tagname
            Tag.assert @tagname, @tagtype
          end
        end
        @tagname = nil # Go back to the annotation dialog
        @parse_path = nil
        if noko_elmt
          noko_elmt[:value] = value
          @annotation = noko_elmt.ancestors.last.to_s
        end
      end
    end
  end

  def update
  end

  def create
  end

  def post
  end

  def destroy
  end

  def show
    x=2
  end

  def set_recipe
    @recipe = Recipe.find params[:id]
  end
end

app/helpers/recipe_contents_helper.rb
require 'scraping/parser.rb'
module RecipeContentsHelper
  def recipe_content recipe_or_decorator
    decorator = recipe_or_decorator.is_a?(Draper::Decorator) ? recipe_or_decorator : recipe_or_decorator.decorate
    with_format('html') { render 'collectible/show_content', decorator: decorator, presenter: present(decorator) }
  end

  def recipe_content_replacement recipe_or_decorator
    [ 'div.content-item', recipe_content(recipe_or_decorator) ]
  end

  # Assert an annotation button in the recipe_contents editor. Give it a title, and declare its token for submission
  def annotation_button token, options={}
    button_options = options.merge(data: {'recipe[recipe_contents][token]' => token},
                                   class: "#{options[:class]} submit-selection",
                                   button_style: nil) # Not a bootstrap button
    dialog_submit_button Parser.token_to_title(token, default: 'Add Name'), button_options
  end

  # Button in the recipe_contents editor to accept a tag. Give it a title, and declare its token for submission
  def tag_usage_button tagtype, tagname, options={}
    button_options = options.merge(data: {'recipe[recipe_contents][tagname]' => tagname},
                                   class: "#{options[:class]} submit-selection",
                                   button_style: nil)
    dialog_submit_button "Accept '#{tagname}' as a new #{Tag.typename(tagtype)}", button_options
  end
end

app/views/recipe_contents/_edit_modal.html.erb
<%=     render('recipe_contents/panel',
               title: @form_title.if_present || 'Replacement Annotator',
               pane_for: :recipe_contents,
               form_variant: @form_name.if_present || 'form',
               wide: true,
               data: {oncancel: recipe_contents_path(@recipe)}
        )
%>

app/views/recipe_contents/_form.html.erb
<%= form_for([:recipe_contents, @recipe], url: annotate_recipe_contents_path(@recipe), html: {class: 'annotate-recipe'}) do |f| %>
  <%= form_errors_helper f %>
  <%# render 'recipe_pages/recipe_fields', f: f %>
  <div class="row">
    <div class="col col-md-12">
      <p>Select a part of the recipe, then click a button to identify it.</p>
    </div>
  </div>
  <input class="content" type="hidden" name="recipe[recipeContents][content]" id="recipe_annotation_content" value="<%= @annotation.if_present || @content.if_present || @recipe.content %>">
  <% if @parse_path %>
    <input class="content" type="hidden" name="recipe[recipeContents][parse_path]" id="recipe_parse_path" value="<%= @parse_path %>">
    <%= dialog_submit_button 'parse it!', class: 'trigger hide' %>
  <% else %>
    <input class="anchorPath" type="hidden" name="recipe[recipeContents][anchor_path]" id="recipe_anchor_path">
    <input class="anchorOffset" type="hidden" name="recipe[recipeContents][anchor_offset]" id="recipe_anchor_offset">
    <input class="focusPath" type="hidden" name="recipe[recipeContents][focus_path]" id="recipe_focus_path">
    <input class="focusOffset" type="hidden" name="recipe[recipeContents][focus_offset]" id="recipe_focus_offset">
  <% end %>
  <div class="row">
    <div class="col-md-5">
      <table>
        <tr>
          <th colspan="1"><%= annotation_button :rp_title, class: 'text-only tag-button tag-button-top' %></th>
          <th colspan="6"><%= annotation_button :rp_inglist, class: 'text-only tag-button tag-button-top', style: 'width: 100%' %></th>
          <th colspan="1">&nbsp;&nbsp;&nbsp;</th>
          <th colspan="1"><%= annotation_button :rp_instructions, class: 'text-only tag-button tag-button-top' %></th>
        </tr>
        <tr>
          <td colspan="1">&nbsp;</td>
          <td colspan="6"><%= annotation_button :rp_ingline, class: 'text-only tag-button tag-button-mdl', style: 'width: 100%' %></td>
          <td colspan="1">
          </td>
          <td colspan="1">
            <%# annotation_button :tag, class: 'text-only', style: 'width: 60%; float: right;' %>
            <%= tag :input, {
                name: 'commit',
                class: 'dialog-submit-button dialog-action-button',
                style: 'position: relative; top: 20px; left: 40px',
                type: 'submit',
                value: "Add Name…",
                data: {'recipe[recipe_contents][token]' => 'tag' } } %>
          </td>
        </tr>
        <tr>
          <td colspan="1">&nbsp;</td>
          <td colspan="2">
            <%= annotation_button :rp_amt, class: 'text-only tag-button tag-button-mdl' %>
          </td>
          <td colspan="2">
            <%= annotation_button :rp_presteps, class: 'text-only tag-button tag-button-mdl' %>
          </td>
          <td colspan="2">
            <%= annotation_button :rp_ingspec, class: 'text-only tag-button tag-button-mdl' %>
          </td>
        </tr>
        <tr>
          <td colspan="1">&nbsp;</td>
          <td colspan="2" class="bottom">
            <%= annotation_button :rp_num, class: 'text-only tag-button tag-button-btm' %>
            <%= annotation_button :rp_unit_tag, class: 'text-only tag-button tag-button-btm' %>
          </td>
          <td colspan="2" class="bottom">
            <%= annotation_button :rp_condition_tag, class: 'text-only tag-button tag-button-btm' %>
          </td>
          <td colspan="2" class="bottom">
            <%= annotation_button :rp_ingredient_tag, class: 'text-only tag-button tag-button-btm' %>
          </td>
        </tr>
      </table>
    </div>
  </div>
<% end %>

<!--Submitting the modified content for final saving; content will be set in JS -->
<%= simple_form_for(@recipe) do |f| %>

  <%# f.hidden_field :content %>
  <input type='hidden' name='recipe[content]' id='recipe_content'>

  <div class='modal-footer'>
    <%= dialog_submit_button 'Done' %>
    <%= dialog_cancel_button 'Revert', data: {:'oncancel' => recipe_contents_path(@recipe)} %>
  </div>
<% end %>

app/views/recipe_contents/_newtag_form.html.erb
<%= form_for([:recipe_contents, @recipe ], url: tag_recipe_contents_path(@recipe), html: { class: 'annotate-recipe' } ) do |f| %>
  <%= form_errors_helper f %>
  <input class="content" type="hidden" name="recipe[recipeContents][content]" id="recipe_annotation_content" value="<%= @content %>">
  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <%= f.label 'Name' %>
        <br/>
        <%= text_field_tag 'recipe[recipeContents][tagname]' %>
      </div>
    </div>
  </div>
  <% if response_service.admin_view? %>
    <div class="row">
      <div class="col-md-12">
        <div class="form-group">
          <%= f.label 'Name for' %>&nbsp;
          <input type="radio" id="ingredient" name="recipe[recipeContents][tagtype]" value="Ingredient" checked>
          <label for="ingredient">&nbsp;Ingredient&nbsp;</label>
          <input type="radio" id="unit" name="recipe[recipeContents][tagtype]" value="Unit">
          <label for="unit">&nbsp;Unit&nbsp;</label>
          <input type="radio" id="condition" name="recipe[recipeContents][tagtype]" value="Condition">
          <label for="condition">&nbsp;Condition</label>
          <%# select_tag 'recipe[recipeContents][tagtype]', tagtype_selections(only: %w{ Ingredient Unit Condition }), style: 'padding: 3px 7px; border-radius: 8px' %>
        </div>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-12">
      It's&nbsp;
      <input type="radio" id="child" name="recipe[recipeContents][tagrelation]" value="parents" checked>
      <label for="child">&nbsp;a kind of&nbsp;</label>
      <input type="radio" id="synonym" name="recipe[recipeContents][tagrelation]" value="synonym">
      <label for="synonym">&nbsp;a synonym for:</label>
      <br>
      <div style="width: 93%; float: right">
        <%= token_input_tag "recipe[recipeContents][tagrelatives]",
                            # :tagtype => @tagtype,
                            :placeholder => "Name(s) of existing category(ies)",
                            :hint => '',
                            :onAdd => 'RP.recipe_contents.onAdd',
                            :onDelete => 'RP.recipe_contents.onDelete',
                            # :tokenLimit => 1,
                            :allowFreeTagging => false,
                            :allowCustomEntry => false
        %>
        <br>
      </div>
    </div>
  </div>
  <div class='row'>
    <div class="col-md-12">
      <%= dialog_submit_button %>
      <%# dialog_cancel_button 'Cancel', data: {:'oncancel' => annotate_recipe_contents_path(@recipe, recipe: { recipeContents: { content: @content } })} %>
      <%= dialog_cancel_button submit_to_cancel: true %>
    </div>
  </div>
<% end %>

app/views/recipe_contents/_panel.html.erb
<%= content_tag :div,
                {
                    class: "dialog modeless notifs-holder #{pane_for.to_s.gsub '_', '-'} new-style green",
                    data: (data if defined?(data))
                }.compact do %>
  <div class="modal-dialog modal-lg" style="width: 700px;">
    <div class="modal-content">
      <%= modal_header title, style: "border-bottom: 1px solid #c0f3c2b5" %>
      <!--Define the pane displayed in the panel-->
      <div class="modal-body">
        <%= render "#{pane_for}/#{form_variant}" %>
      </div>
    </div>
  </div>
<% end %>

app/views/recipe_contents/_tagtype_form.html.erb
<%= form_for([:recipe_contents, @recipe], url: annotate_recipe_contents_path(@recipe), html: {class: 'annotate-recipe'}) do |f| %>
  <%= form_errors_helper f %>
  <input class="content" type="hidden" name="recipe[recipeContents][content]" id="recipe_annotation_content" value="<%= @annotation.if_present || @recipe.content %>">
  <input class="tagname" type="hidden" name="recipe[recipeContents][tagname]" id="recipe_annotation_tagname" value="<%= @tagname %>">
  <input class="tagtype" type="hidden" name="recipe[recipeContents][tagtype]" id="recipe_annotation_tagtype" value="<%= @tagtype %>">
  <input class="parse_path" type="hidden" name="recipe[recipeContents][parse_path]" id="recipe_annotation_content" value="<%= @parse_path %>">
  <div class="row">
    <div class="col col-md-7">
      <p>Is '<%= @tagname %>' really a new <%= Tag.typename(@tagtype) %>, or is it another name for something else--and if so, what would that be?</p>
    </div>
  </div>
  <div class="row">
    <div class="col col-md-12">
      <%= tag_usage_button @tagtype, @tagname, class: 'text-only tag-button dialog-action-button' %>
    </div>
  </div>
  <div class="row" >
    <div class="col col-md-12">
      <div style="display: inline-block; vertical-align: top; font-size: 1.1em; margin-top: 0.4em; margin-left: 1em; margin-bottom: 0.6em">No,
        it really refers to:
      </div>
      <div style="display: inline-block; width:400px">
        <%= token_input_tag "recipe[recipeContents][replacement]",
                            :tagtype => @tagtype,
                            :placeholder => "Find existing #{Tag.typename(@tagtype)}",
                            :hint => '',
                            :onAdd => 'RP.recipe_contents.onAdd',
                            :onDelete => 'RP.recipe_contents.onDelete',
                            :tokenLimit => 1,
                            :allowFreeTagging => false,
                            :allowCustomEntry => false
        %>
      </div>
    </div>
  </div>
  <div class="row" >
    <div style='display: inline-block; width: 60px'></div>
    <%= check_box_tag 'recipe[recipeContents][assert]', '1', false, disabled: true %>&nbsp;&#8230;plus, recognize it as a synonym in future
    <%= dialog_submit_button disabled: true %>
    <%= dialog_cancel_button submit_to_cancel: true %>
  </div>
<% end %>

app/views/recipe_contents/create.html.erb
<h1>RecipeContents#create</h1>
<p>Find me in app/views/recipe_contents/create.html.erb</p>

app/views/recipe_contents/destroy.html.erb
<h1>RecipeContents#destroy</h1>
<p>Find me in app/views/recipe_contents/destroy.html.erb</p>

app/views/recipe_contents/edit.html.erb
<h1>RecipeContents#edit</h1>
<p>Find me in app/views/recipe_contents/edit.html.erb</p>

app/views/recipe_contents/patch.html.erb
<h1>RecipeContents#patch</h1>
<p>Find me in app/views/recipe_contents/patch.html.erb</p>

app/views/recipe_contents/post.html.erb
<h1>RecipeContents#post</h1>
<p>Find me in app/views/recipe_contents/post.html.erb</p>

app/views/recipe_contents/show.html.erb
<h1>RecipeContents#show</h1>
<p>Find me in app/views/recipe_contents/show.html.erb</p>