config/routes.rb
RP::Application.routes.draw do
  resources :offerings
  resources :editions

  get 'rp_events/show'

  get 'rp_events/show_page'

  get 'rp_events/index'

  get 'rp_events/new'

  get 'rp_events/create'

  get 'rp_events/update'

  get 'rp_events/destroy'

  get 'scraper/new'
  post 'scraper/create'
  post 'scraper/init'

  get 'finders/create'
  post 'finders/create'

  concern :picable do
    member do
      get 'editpic' # Open dialog to acquire an image from various sources
      get 'glean/:what', :action => 'glean', :what => /titles|descriptions|images|feeds|table|card|masonry|slider/, :as => 'glean'
    end
  end

  concern :collectible do
    member do
      get 'touch'
      get 'associated'
      patch 'collect'
      get 'card' # Provide a card for display via JSON
    end
  end

  concern :taggable do
    member do
      get 'tag' # Present the dialog for tagging and commenting
      patch 'tag'
      get 'lists'  # Present the dialog for managing the lists it's on
      patch 'lists'
    end
  end

  get 'search/index'

  resources :recipe_pages, :concerns => [:taggable, :collectible, :picable]

  resources :page_refs, :concerns => [:taggable, :collectible, :picable] do
    collection do
      get 'tag'
      put 'create'
      post 'create'
    end
  end

  resources :referments, :only => [:show, :create, :update, :destroy] do
    collection do
      put 'create'
    end
  end

  resources :tagsets

  resources :answers

  if Rails.env.staging?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  get "admin/toggle"
  resources :feed_entries, :except => [:index, :create, :new], :concerns => [:taggable, :collectible, :picable]

  resources :suggestions do
    member do
      get 'results'
    end
  end

  if Rails.env.development? || Rails.env.test?
    get "integers" => 'integers#index'
  end

  post '/votes/:entity/:id' => 'votes#create', :entity => /recipe|feed|feed_entry|list|product|site|user|referent/

  get "redirect/go", :as => "goto"
  put "redirect/go"
  get '/auth/failure' => 'authentications#failure'
  get 'defer_invitation' => 'application#defer_invitation'
  get 'menu' => 'application#menu'
  resources :authentications

  get '/auth/:provider/callback' => 'authentications#create'
  post '/auth/:provider/callback' => 'authentications#create'

  devise_for :users, :skip => [:registrations], :controllers => {
                       :sessions => 'sessions',
                       :passwords => 'passwords',
                       :invitations => 'invitations',
                   }

  match 'users', :controller => 'users', :action => 'index', :via => [:get, :post]

  devise_scope :user do
    put "/users/password/new" => 'passwords#new' # To handle redirects from edit
    post "/users/register" => "registrations#create", :as => "user_registration"
    get "/users/sign_up" => "registrations#new", :as => "new_user_registration"
    get "/users/edit" => "registrations#edit", :as => "edit_user_registration"
    get "/users/cancel" => "registrations#cancel", :as => "cancel_user_registration"
    put "/users" => "registrations#update"
    delete "/users" => "registrations#destroy"
    get "/users/sign_out" => "sessions#destroy"
    patch "/users" => "registrations#update"

    get "/users/invitation/divert" => "invitations#divert", :as => "divert_user_invitation"

  end

  authenticate do
    notify_to :users, with_devise: :users, controller: 'users/notifications_with_devise'
  end

  get 'users/profile' => 'users#profile'
  get 'users/identify' => 'users#identify'
  get 'users/:id/recent' => 'users#recent', :as => "user_recent"
  get 'users/:id/recent' => 'users#recent', :as => "user_root"
  get 'users/:id/collection' => 'users#collection', :as => "collection_user"
  get 'users/:id/biglist' => 'users#biglist', :as => "user_biglist"
  resources :users, :except => [:index, :create], :concerns => [ :picable, :taggable, :collectible] do
    member do
      get 'match_friends'
      get 'notify'
      get 'acquire' # Acquire a recipe (etc.)
      post 'follow'
      get 'getpic'
      patch 'sendmail'
      get 'unsubscribe'
      get 'sendmail', :as => "mailto"
    end
  end

  post '/list' => 'lists#create', :as => 'create_list'
  resources :lists, except: [:index, :create], :concerns => [:picable, :taggable, :collectible] do
    member do
      post 'pin' # Add an entity to a list
      get 'contents'
    end
  end
  match 'lists', :controller => 'lists', :action => 'index', :via => [:get, :post]

  post '/site' => 'sites#create', :as => 'create_site'
  resources :sites, except: [:index, :create], :concerns => [:picable, :collectible, :taggable] do
    member do
      post 'absorb'
      get 'feeds'
      post 'approve' # (Admin only) approve the site for presentation
    end
  end
  match 'sites', :controller => 'sites', :action => 'index', :via => [:get, :post]

  resources :image_references #, :except => [:index, :create]
  resources :gleanings
  resources :mercury_results

  post '/feed' => 'feeds#create', :as => 'create_feed'
  resources :feeds, :except => [:index, :create], :concerns => [:picable, :collectible, :taggable] do
    member do
      get 'refresh' # Refresh the feed's entries
      get 'contents'
      post 'approve' # (Admin only) approve the feed for presentation
      post 'rate'
    end
  end
  match 'feeds', :controller => 'feeds', :action => 'index', :via => [:get, :post]

  resources :tag_selections

  post '/tag' => 'tags#create', :as => 'create_tag'
  resources :tags, except: [:index, :create] do
    member do
      post 'associate'
      get 'owned'
      get 'associated'
      post 'define'
    end
    collection do
      get 'list'
      get 'typify'
      get 'match'
    end
  end
  match 'tags', :controller => 'tags', :action => 'index', :via => [:get, :post]

  match 'search', :controller => 'search', :action => 'index', :via => :get
=begin
  post 'collection/update'
  get "collection/refresh"
  get "collection/feed"
  get "collection/show", as: 'collection_show'
  get "collection/new"
  get "collection/edit"
  post "collection/create"
  get "collection/relist"

  get "stream/stream"
  get "stream/buffer_test"
=end

  get 'iframe/create'
  get 'admin/data'
  get 'admin/control'

  resources :feedback, :only => [:new, :create]
  resources :expressions
  resources :referents, :concerns => [:picable, :collectible, :taggable] do
    member do
      get 'associated'
    end
  end
  resources :ratings
  resources :scales

  resources :recipes, :concerns => [:picable, :collectible, :taggable] do
    member do
      get 'piclist'
      get :recipe_page
      post :recipe_page
      resource :recipe_contents do
        get 'annotate'
        patch 'annotate'
        get 'tag'
        patch 'tag'
      end
    end
    collection do
      get 'capture'
      post 'parse'
    end
  end
  get '/revise', :to => 'recipes#revise'
  get '/scrape', :to => 'page_refs#scrape'

  get '/home', :to => 'pages#home'
  get '/privacy', :to => 'pages#privacy'
  get '/popup/:name', :to => 'pages#popup'
  get '/popup', :to => 'pages#popup'
  get '/share', :to => 'pages#share'
  get '/tell_me_more', :to => 'pages#tell_me_more'
  get '/contact', :to => 'pages#contact'
  get '/about', :to => 'pages#about'
  get '/mission', :to => 'pages#mission'
  get '/welcome', :to => 'pages#welcome'
  get '/faq', :to => 'pages#faq'
  get '/admin', :to => 'pages#admin'
  get '/sprites', :to => 'pages#sprites'
  get '/cookmark', :to => 'pages#cookmark'
  get '/collect', :to => 'pages#collect'
  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'
  root :to => 'pages#root'

end

app/helpers/tags_helper.rb
module TagsHelper

  # Helper to define a selection menu for tag type
  def tagtype_selections val = nil, only: nil, except: %i{ List Epitaph }
    selections = Tag.type_selections withnull: val.kind_of?(Tag), only: only, except: except
    if course_ix = selections.find_index( ['Course', 18] ) # Move 'Course' to an earlier spot in the array
      selections.insert 3, selections.delete_at(course_ix)
    end
    if null_ix = selections.find_index(['Random', 0])
      selections[null_ix][0] = 'No Type'
    end
    if val.kind_of? Tag
      options_for_select selections, val.typenum
    elsif val.nil?
      options_for_select selections
    else
      options_for_select selections, val
    end
  end

  # Provide a Bootstrap selection menu of a set of tags
  def tag_select alltags, curtags
    menu_options = {class: "question-selector"}
    menu_options[:style] = "display: none;" if (alltags - curtags).empty?
    options = alltags.collect {|tag|
      content_tag :option, tag.name, {value: tag.id, style: ("display: none;" if curtags.include?(tag))}.compact
    }.unshift(
        content_tag :option, "Pick #{curtags.empty? ? 'a' : 'Another'} Question", value: 0
    ).join.html_safe
    content_tag :select, options, menu_options # , class: "selectpicker"
  end

  # Summarize a tag similar to this one.
  # options:
  #   absorb_btn: a button to absorb the other tag into this one
  #   merge_into_btn: a button to absorb this tag into the other one
  def summarize_tag_similar this, other, options = {}
    contents = [
        homelink(other),
        "(#{other.typename})"
    ]
    contents << button_to_submit('Absorb',
                                 associate_tag_path(this, other: other.id, as: 'absorb', format: 'json'),
                                 :xs,
                                 mode: :modal,
                                 with_form: true,
                                 class: 'absorb_button',
                                 id: "absorb_button_#{other.id}") if options[:absorb_btn]
    contents << button_to_submit('Merge Into',
                                 associate_tag_path(this, other: other.id, as: 'merge_into', format: 'json'),
                                 :xs,
                                 mode: :modal,
                                 with_form: true,
                                 class: 'absorb_button',
                                 id: "merge_into_button_#{this.id}") if options[:merge_into_btn]
    content_tag :span, safe_join(contents, ' '), class: "absorb_#{other.id}"
  end

  def tag_filter_header locals = {}
    locals[:type_selector] ||= false
    render "tags/tag_filter_header", locals # ttl: label, type_selector: type_selector
  end

  def tag_list tags
    strjoin(tags.collect {|tag|
      link_to_dialog tag.name, tag_path(tag)
    }).html_safe
  end

  def list_tags_for_collectible taglist, collectible_decorator = nil
    tags_str = safe_join taglist.collect {|tag|
      link_to_submit tag.name, linkpath(tag), :mode => :partial, :class => 'taglink'
    }, '&nbsp;<span class="tagsep">|</span> '.html_safe
=begin
    collectible_decorator ?
        safe_join( [ tags_str, collectible_tag_button(collectible_decorator)], '&nbsp; '.html_safe ) :
        tags_str
=end
  end
end

app/views/tags/_alert_form.html.erb
<%= form_for(@tag) do |f| %>
    <%= tag :input, type: 'hidden', name: 'mode', value: 'modal' %>
    <%= tag :input, type: 'hidden', name: 'button_name', id: 'button_name' %>
    <%= f.hidden_field :name %>
    <%= f.hidden_field :tagtype %>
    <div class="row">
      <div class="col-md-12">
        <div class="alert-msg">'<%= @tag.name %>' is already defined as <%= @oldtype.with_article %>.
          <br>Do you mean it should be <%= @tag.typename.with_article %> and <strong>not</strong> <%= @oldtype.with_article %>,
          <br>or be defined as <strong>both</strong> <%= @oldtype %> <strong>and</strong> <%= @tag.typename %>?
        </div>
      </div>
    </div>
    <%= modal_footer do %>
        <%# form_actions f, submit_label: 'Move', class: "btn btn-success", style: "margin-top: 10px;" %>
        <div class='form-group actions'>
          <%= dialog_cancel_button %>
          <%= dialog_answer_button 'Duplicate', button_style: 'success' %>
          <%= dialog_answer_button 'Move', button_style: 'primary' %>
        </div>
    <% end %>
<% end %>

app/views/tags/_alltags.html.erb
<div id="alltags" >
  <% unless @taglist.empty? %>
	<table>
	  <tr class="list_header">
	    <th class="list_header">ID</th>
	    <th>Name</th>
	    <th>Type</th>
		<th></th>
		<th>Public?</th>
		<th>Similar</th>
	    <th>Synonym(s)</th>
	    <th>Meaning(s)</th>
		<% if policy(@taglist.first).edit? %>
	      <th></th>
	      <th></th>
		<% end %>
	  </tr>
		<% @taglist.each do |tag| %>
			<% @tag = tag %>
			<%= render 'show_table' %>
		<% end %>
	</table>
  <% else %>
	<p class="airy">...Sorry, no tags match.</p>
  <% end %>
  <%= link_to 'New Tag', new_tag_path %>
</div>

app/views/tags/_edit_page.html.erb
<h3>Edit Tag</h3>
<%= render 'form' %>
<hr>
<%= link_to_dialog 'Tag Info', @tag %> |
<%= link_to_submit 'Tags List', tags_path %>

app/views/tags/_filtertag.html.erb
<%# Form for the tag filtering the tag list %>
<%= form_for(@filtertag) do |f| %>
    Filter by: <%= f.text_field :name %>
    <%= f.select(:tagtype, tagtype_selections(@filtertag), include_blank: true) %>
    <%= f.submit "Filter List" %>
<% end %>

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
    <%= tag :input, type: 'hidden', name: 'mode', value: 'modal' %>
    <div class="row">
      <div class="col-md-12">
        <div class="form-group">
          <%= f.label :name %>
          <br/>
          <%= f.text_field :name %>
        </div>
      </div>
    </div>
    <% if response_service.admin_view? %>
        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <%= f.label :type %>&nbsp;<%= f.select :tagtype, tagtype_selections(@tag) %>
            </div>
          </div>
        </div>
    <% end %>
    <%= modal_footer do %>
        <%= form_actions f, submit_label: (@tag.id ? "Update Tag" : "Create Tag"), class: "btn btn-success", style: "margin-top: 10px;" %>
    <% end %>
<% end %>

app/views/tags/_form_synonym.html.erb
<!--<label class="string optional">Child of</label>-->
<%= form_tag(associate_tag_path(presenter.tag, as: 'synonym'), class: 'submit', method: 'post') do %>
    Make synonym of:<br>
    <%= token_input_tag :other,
                        :tokenLimit => 1,
                        :noResultsText => 'No such tag found',
                        :tagtype => (presenter.tag.tagtype if presenter.tag.tagtype > 0),
                        :tagtype_x => [0, :List],
                        :query => { all: true, except: presenter.tag.id, verbose: true, disambiguate: true }, # See TagsController#match
                        :allowFreeTagging => (presenter.tag.tagtype > 0),
                        :allowCustomEntry => (presenter.tag.tagtype > 0)
    %>
<% end %>

app/views/tags/_index.html.erb
<%= link_to_dialog 'New Tag', new_tag_path %>

app/views/tags/_index_page.html.erb
<%= render "index" %>

app/views/tags/_new_modal.html.erb
<%= modal_dialog :new_tag, "Create Tag" do %>
    <%= render 'form' %>
<% end %>

app/views/tags/_new_page.html.erb
<h3>Make New Tag</h3>

<%= render 'form' %>
<hr>
<%= link_to 'Tags List', tags_path %>

app/views/tags/_show_table_item.html.erb
<% item ||= @tag %>
<% @tagserv = TagServices.new item %>
<tr id="<%= dom_id item %>">
  <td class="tag_type"><%= item.id.to_s %></td>
  <td><%= summarize_tag %></td>
  <td><%= select_tag :tagtype, options_from_collection_for_select(Tag.type_selections(true), :last, :first, item.tagtype),
                     class: "tag_type_selector",
                     onchange: "RP.change(event);",
                     data: {request: "/tags/typify",
                            valueparam: "typenum",
                            querydata: {tagid: item.id}} %></td>
  <td>
    <%= summarize_tag_recipe_count %>
    <%= summarize_tag_owner_count %>
    <%= summarize_tag_parents_count %>
    <%= summarize_tag_children_count %>
    <%= summarize_tag_reference_count %>
  </td>
  <td>
    <%= @tagserv.isGlobal ? "Y" : "N" %>
  </td>
  <td>
    <%= summarize_tag_similars label: "", absorb_btn: true, joiner: "<br>" %>
  </td>
  <td>
    <%= summarize_tag_synonyms "" %>
  </td>
  <td>
    <% item.referents.each do |ref| %>
        <%= link_to_submit ref.name, referent_path(ref), mode: :modal %><%= ", " unless ref == item.referents.last %>
    <% end %>
  </td>
  <% if permitted_to? :edit, item %>
      <td>
        <%= link_to_modal 'Edit', edit_tag_path(item) %>
      </td>
      <td>
        <%= link_to 'Destroy', item, data: { confirm: 'Are you sure?'}, method: :delete %>
      </td>
  <% end %>
</tr>

app/views/tags/_stream_shell.html.erb
<%= render "shared/stream_table", headers: [ "ID", "Name", "Type", "", "Public?", "Similar", "Synonym(s)", "Meaning(s)", "", "" ] %>

app/views/tags/_tag_controls.html.erb
<div class="control-group">
  <label class="string optional"><%= label %>(s)<br><span class="locked-tags"><%= locked_tags %></span></label>
  <input type="text"
         class="token-input-field-pending"
         id="<%= tokens_id %>"
         name="<%= decorator.field_name tokens_id %>"
         rows="2"
         size="30"
         placeholder="<%= label.pluralize %>"
         data-tagtype="<%= tagtypes %>"
         data-pre="<%= data_pre %>"/>
  <%= extras if defined?(extras) %>
</div>

app/views/tags/index.html.erb
<%= tag_filter_header title: "Tags" %>
<%= link_to_dialog 'New Tag', new_tag_path %>
<%= render "shared/stream_results_placeholder" %>